---
- name: Include convert from netplan
  include: convert-from-netplan.yml
  tags:
    - netplan

- name: Include base
  include: base.yml
  tags:
    - base

- name: Include postgresql
  include: postgresql.yml
  tags:
    - postgresql

- name: Include maas
  include: maas.yml
  tags:
    - maas

- name: Include reconfig database
  include: reconfig_database.yml
  tags:
    - db

- name: Include access master
  include: access_master.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - iptables

- name: Include replication
  include: replication.yml
  when: "'maas-slave' in inventory_hostname"
  tags:
    - replication
