---
- name: Include bootstrap
  include: bootstrap.yml
  tags:
    - bootstrap

- name: Include convert from netplan
  include: convert-from-netplan.yml
  tags:
    - netplan

- name: Include naturalis.base role
  include_role:
    name: naturalis.base
  tags:
    - base

- name: Include postgresql role
  include_role:
    name: postgresql
  tags:
    - postgresql

- name: Include MAAS role
  include_role:
    name: ansible-maas
  tags:
    - maas

- name: Include reconfig database
  include: reconfig_database.yml
  tags:
    - db

- name: Include access master
  include: access_master.yml
  when: "'postgresql-master' in inventory_hostname"
  tags:
    - iptables

- name: Include replication
  include: replication.yml
  when: "'postgresql-slave' in inventory_hostname"
  tags:
    - replication
