- name: Setup replication | check if replication has been started
  stat:
    path: /etc/postgresql/.replica_started
  register: "replica_started"

- name: Setup replication | stop postgresql service
  systemd:
    name: postgresql
    state: stopped
  when: not replica_started.stat.exists

- name: Setup replication | cleanup postgresql dir
  file:
    path: "{{ postgresql_data_directory }}"
    state: absent
  when: not replica_started.stat.exists

# TODO: use variable to refer to postgresql-master
- name: Setup replication | start replica
  command: >
    pg_basebackup
      --host=172.16.168.1
      --username=replicator
      --write-recovery-conf
      --pgdata={{ postgresql_data_directory }}
      --progress
  become_user: postgres
  when: not replica_started.stat.exists

- name: Setup replication | start postgresql service
  systemd:
    name: postgresql
    state: started
  when: not replica_started.stat.exists

- name: Setup replication | set replication started file
  copy:
    dest: "/etc/postgresql/.replica_started"
    content: "if you remove this file, ansible will recreate replication"
    owner: postgres
    group: postgres
    mode: 0400
